//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

//#import "AWECommentCellProtocol-Protocol.h"
//#import "AWEUserMessage-Protocol.h"

@class AWECommentAnchorView, AWECommentModel, AWECommentPostStateView, AWEInsetsLabel, AWEToolTipView, AWEUserNameLabel, NSDictionary, NSString, UIButton, UIImageView, UILabel, UILongPressGestureRecognizer, UITapGestureRecognizer, UIView, YYAnimatedImageView, YYLabel;

@interface AWECommentPanelBaseCell : UITableViewCell
{
    _Bool _isLikeBtnAnimated;	// 8 = 0x8
    _Bool _isDislikeBtnAnimated;	// 9 = 0x9
    id avatarOrNameTappedBlock;	// 16 = 0x10
    NSString *cityInfoString;	// 24 = 0x18
    id handleLongPressBlock;	// 32 = 0x20
    id likeButtonTappedBlock;	// 40 = 0x28
    NSDictionary *logExtraDict;	// 48 = 0x30
    NSString *referString;	// 56 = 0x38
    id retryPostBlock;	// 64 = 0x40
    long long sceneType;	// 72 = 0x48
    id replyLabelTappedBlock;	// 80 = 0x50
    NSString *itemUserID;	// 88 = 0x58
    id exitLandscapeBlock;	// 96 = 0x60
    AWECommentModel *_commentModel;	// 104 = 0x68
    UITapGestureRecognizer *_reloadStickerGR;	// 112 = 0x70
    AWECommentModel *_mainComment;	// 120 = 0x78
    AWECommentModel *_quotedCommentModel;	// 128 = 0x80
    UIView *_highlightBackgroundView;	// 136 = 0x88
    UIImageView *_avatarView;	// 144 = 0x90
    UIView *_avatarBorderView;	// 152 = 0x98
    AWEUserNameLabel *_nameLabel;	// 160 = 0xa0
    YYLabel *_commentLabel;	// 168 = 0xa8
    UIButton *_likeButton;	// 176 = 0xb0
    UIButton *_dislikeButton;	// 184 = 0xb8
    UILabel *_likesLabel;	// 192 = 0xc0
    YYAnimatedImageView *_stickerImgView;	// 200 = 0xc8
    YYLabel *_timeLabel;	// 208 = 0xd0
    AWECommentPostStateView *_postStateView;	// 216 = 0xd8
    UILabel *_likedByCreatorLabel;	// 224 = 0xe0
    AWEInsetsLabel *_customTagLabel;	// 232 = 0xe8
    AWEInsetsLabel *_authorTagLabel;	// 240 = 0xf0
    AWEInsetsLabel *_followerOrNearbyTagLabel;	// 248 = 0xf8
    AWEInsetsLabel *_reposterTagLabel;	// 256 = 0x100
    AWEInsetsLabel *_relationTagLabel;	// 264 = 0x108
    AWEToolTipView *_tagToolTipView;	// 272 = 0x110
    UILongPressGestureRecognizer *_longPressGestureRecognizer;	// 280 = 0x118
    id _generator;	// 288 = 0x120
    UIView *_lineView;	// 296 = 0x128
    AWECommentAnchorView *_musicAnchorView;	// 304 = 0x130
    AWECommentAnchorView *_extraAnchorView;	// 312 = 0x138
    UILabel *_replyLabel;	// 320 = 0x140
    UIImageView *_replyImageView;	// 328 = 0x148
    UILabel *_replyUserLabel;	// 336 = 0x150
}

+ (id)identifier;	// IMP=0x00000001045a321c

@property(retain, nonatomic) UILabel *replyUserLabel; // @synthesize replyUserLabel=_replyUserLabel;
@property(retain, nonatomic) UIImageView *replyImageView; // @synthesize replyImageView=_replyImageView;
@property(retain, nonatomic) UILabel *replyLabel; // @synthesize replyLabel=_replyLabel;
@property(retain, nonatomic) AWECommentAnchorView *extraAnchorView; // @synthesize extraAnchorView=_extraAnchorView;
@property(retain, nonatomic) AWECommentAnchorView *musicAnchorView; // @synthesize musicAnchorView=_musicAnchorView;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) id generator; // @synthesize generator=_generator;
@property(retain, nonatomic) UILongPressGestureRecognizer *longPressGestureRecognizer; // @synthesize longPressGestureRecognizer=_longPressGestureRecognizer;
@property(retain, nonatomic) AWEToolTipView *tagToolTipView; // @synthesize tagToolTipView=_tagToolTipView;
@property(retain, nonatomic) AWEInsetsLabel *relationTagLabel; // @synthesize relationTagLabel=_relationTagLabel;
@property(retain, nonatomic) AWEInsetsLabel *reposterTagLabel; // @synthesize reposterTagLabel=_reposterTagLabel;
@property(retain, nonatomic) AWEInsetsLabel *followerOrNearbyTagLabel; // @synthesize followerOrNearbyTagLabel=_followerOrNearbyTagLabel;
@property(retain, nonatomic) AWEInsetsLabel *authorTagLabel; // @synthesize authorTagLabel=_authorTagLabel;
@property(retain, nonatomic) AWEInsetsLabel *customTagLabel; // @synthesize customTagLabel=_customTagLabel;
@property(retain, nonatomic) UILabel *likedByCreatorLabel; // @synthesize likedByCreatorLabel=_likedByCreatorLabel;
@property(retain, nonatomic) AWECommentPostStateView *postStateView; // @synthesize postStateView=_postStateView;
@property(retain, nonatomic) YYLabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) YYAnimatedImageView *stickerImgView; // @synthesize stickerImgView=_stickerImgView;
@property(retain, nonatomic) UILabel *likesLabel; // @synthesize likesLabel=_likesLabel;
@property(retain, nonatomic) UIButton *dislikeButton; // @synthesize dislikeButton=_dislikeButton;
@property(retain, nonatomic) UIButton *likeButton; // @synthesize likeButton=_likeButton;
@property(retain, nonatomic) YYLabel *commentLabel; // @synthesize commentLabel=_commentLabel;
@property(retain, nonatomic) AWEUserNameLabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIView *avatarBorderView; // @synthesize avatarBorderView=_avatarBorderView;
@property(retain, nonatomic) UIImageView *avatarView; // @synthesize avatarView=_avatarView;
@property(retain, nonatomic) UIView *highlightBackgroundView; // @synthesize highlightBackgroundView=_highlightBackgroundView;
@property(retain, nonatomic) AWECommentModel *quotedCommentModel; // @synthesize quotedCommentModel=_quotedCommentModel;
@property(retain, nonatomic) AWECommentModel *mainComment; // @synthesize mainComment=_mainComment;
@property(retain, nonatomic) UITapGestureRecognizer *reloadStickerGR; // @synthesize reloadStickerGR=_reloadStickerGR;
@property(nonatomic) _Bool isDislikeBtnAnimated; // @synthesize isDislikeBtnAnimated=_isDislikeBtnAnimated;
@property(nonatomic) _Bool isLikeBtnAnimated; // @synthesize isLikeBtnAnimated=_isLikeBtnAnimated;
@property(retain, nonatomic) AWECommentModel *commentModel; // @synthesize commentModel=_commentModel;
@property(copy, nonatomic) id exitLandscapeBlock; // @synthesize exitLandscapeBlock;
@property(copy, nonatomic) NSString *itemUserID; // @synthesize itemUserID;
@property(copy, nonatomic) id replyLabelTappedBlock; // @synthesize replyLabelTappedBlock;
@property(nonatomic) long long sceneType; // @synthesize sceneType;
@property(copy, nonatomic) id retryPostBlock; // @synthesize retryPostBlock;
@property(copy, nonatomic) NSString *referString; // @synthesize referString;
@property(copy, nonatomic) NSDictionary *logExtraDict; // @synthesize logExtraDict;
@property(copy, nonatomic) id likeButtonTappedBlock; // @synthesize likeButtonTappedBlock;
@property(copy, nonatomic) id handleLongPressBlock; // @synthesize handleLongPressBlock;
@property(copy, nonatomic) NSString *cityInfoString; // @synthesize cityInfoString;
@property(copy, nonatomic) id avatarOrNameTappedBlock; // @synthesize avatarOrNameTappedBlock;
- (id)commentContext;	// IMP=0x00000001045b1058
- (Class)commentPanelCellConfiguration;	// IMP=0x00000001045b1044
- (_Bool)updateTagToolTipIfNeeded:(id)arg1 onView:(id)arg2 forceDismiss:(_Bool)arg3;	// IMP=0x00000001045b0e7c
- (_Bool)dismissTagToolTip:(id)arg1;	// IMP=0x00000001045b0be4
- (_Bool)showTagToolTip:(id)arg1 onView:(id)arg2;	// IMP=0x00000001045b0358
- (void)didFinishSetRemarkWithUser:(id)arg1;	// IMP=0x00000001045ae598
- (void)didFinishBlockUser:(id)arg1 status:(long long)arg2;	// IMP=0x00000001045ae45c
- (void)didFinishUnFollowUser:(id)arg1 status:(long long)arg2 error:(id)arg3;	// IMP=0x00000001045ae2f8
- (void)p_reloadSticker;	// IMP=0x00000001045adedc
- (void)updateLikedByCreator;	// IMP=0x00000001045add60
- (void)updateLikeStateWithAnimation:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x00000001045ad430
- (void)_executeTapAlphaAnimation:(id)arg1 reverse:(_Bool)arg2;	// IMP=0x00000001045ad358
- (_Bool)checkNeedAnimation:(id)arg1 reverse:(_Bool)arg2;	// IMP=0x00000001045ad224
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;	// IMP=0x00000001045ad18c
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;	// IMP=0x00000001045ad0f4
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;	// IMP=0x00000001045ad05c
- (void)__jumpToSubpage:(id)arg1 didLoginAction:(id)arg2;	// IMP=0x00000001045acf24
- (void)__jumpToSubpage:(id)arg1;	// IMP=0x00000001045ace88
- (void)replyLabelTapped;	// IMP=0x00000001045acb70
- (void)clearAnimatedImageBuffer;	// IMP=0x00000001045acb30
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;	// IMP=0x00000001045acb1c
- (_Bool)canBecomeFirstResponder;	// IMP=0x00000001045acb14
- (void)p_addSticker;	// IMP=0x00000001045aca7c
- (void)p_showStickerLongPressMenu;	// IMP=0x00000001045ac848
- (void)resetLikesLabel;	// IMP=0x00000001045ac7ec
- (void)relationTagLabelTapped:(id)arg1;	// IMP=0x00000001045ac4cc
- (void)linkHighlightTapped:(id)arg1 inRange:(struct _NSRange)arg2;	// IMP=0x00000001045abc30
- (void)likeButtonTapped;	// IMP=0x00000001045ab67c
- (void)commentUserTapped:(id)arg1;	// IMP=0x00000001045a8a6c
- (void)replyUserTapped:(id)arg1;	// IMP=0x00000001045a8950
- (void)handleLongPress:(id)arg1;	// IMP=0x00000001045a8774
- (void)updateReplyUserLabel;	// IMP=0x00000001045a85bc
- (void)updateNameLabel;	// IMP=0x00000001045a8458
- (_Bool)shouldHideReplyLabel;	// IMP=0x00000001045a8450
- (_Bool)appendStickerAttachment;	// IMP=0x00000001045a8448
- (_Bool)showTimestampAfterComment;	// IMP=0x00000001045a8440
- (_Bool)needLongPressGesture;	// IMP=0x00000001045a8438
- (_Bool)canShowLikedByCreatorLabel;	// IMP=0x00000001045a8430
- (_Bool)showLikesButton;	// IMP=0x00000001045a839c
- (_Bool)showLikesLabel;	// IMP=0x00000001045a8270
- (void)fixDiggCount;	// IMP=0x00000001045a807c
- (id)displayTimeText;	// IMP=0x00000001045a7f7c
- (id)p_timeLabelAttributedString:(_Bool)arg1;	// IMP=0x00000001045a7d7c
- (id)displayAttrContent;	// IMP=0x00000001045a71b0
- (id)replyUserContent;	// IMP=0x00000001045a6ff8
- (id)displayContent;	// IMP=0x00000001045a6f08
- (id)authorName;	// IMP=0x00000001045a6ea4
- (void)highlight;	// IMP=0x00000001045a6c50
- (void)setupUI;	// IMP=0x00000001045a643c
- (void)prepareForReuse;	// IMP=0x00000001045a63e8
- (void)showTagDetailH5;	// IMP=0x00000001045a6040
- (_Bool)shouldShowLikedByCreatorLabel;	// IMP=0x00000001045a5f44
- (void)configWithComment:(id)arg1;	// IMP=0x00000001045a3578
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x00000001045a32f0
- (void)dealloc;	// IMP=0x00000001045a32a0
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x00000001045a3238

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

